FROM platform_front_ui:prereq

WORKDIR /app

ADD . /app

# RUN gatsby telemetry --disable

# RUN gatsby build

# CMD ln -s /prereq/node_modules ./ & gatsby serve --host=0.0.0.0 --port 8001

# ENV INTERNAL_STATUS_PORT 8002
ENV INTERNAL_STATUS_PORT 30150

RUN gatsby telemetry --disable

CMD ln -s /prereq/node_modules ./ & ./migrate.sh